[workspace]
authors = ["Zahra Khorasani <zahra.khorasani@nbis.se>"]
channels = ["conda-forge"]
name = "Article_Finder"
platforms = ["osx-arm64","osx-64","linux-64","win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"

[pypi-dependencies]
pandas = ">=2.0"
requests = ">=2.31"
python-dotenv = ">=1.0"
pyyaml = ">=6.0"
marimo = ">=0.19.2, <0.20"
